### PR TITLE
chore: fix test action by giving it appropriate permissions

### PR DESCRIPTION
**Pull request by lazysoundsystem**
An attempt to fix https://github.com/UN-OCHA/ocha-api-site/actions/runs/10797377121/job/29991357544:
```
Run slavcodev/coverage-monitor-action@v1
Error: Resource not accessible by integration
```
as suggested in https://stackoverflow.com/a/77809124

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
Maybe those weren't the appropriate permissions...

I tried that approach because the other answer refers to settings I don't have access to: https://stackoverflow.com/questions/75995802/resource-not-accessible-by-integration-github-action-fails-for-pushed-commit/76199390#76199390.

Perhaps you do, @cafuego ?

**Comment by lazysoundsystem** [comment]
Also, see https://github.com/orgs/community/discussions/60820

**Comment by cafuego** [comment]
I just copied and pasted the snippet that worked on all other repos ;-)

**Review by cafuego — APPROVED** [review]

**Comment by lazysoundsystem** [comment]
Aha, I should have looked there first. Thanks!

**Pull request merged**
