### PR TITLE
chore: Bump PHP

### PR DESCRIPTION
**Pull request by cafuego**
And related purposes.

### CODE REVIEW

**Comment by cafuego** [comment]
Well, this turned into a rather large episode of "How To Shave Your Yak" but I *think* all that remains now are deprecations. Assigning to @attiks so he can at least have a look when he feels better.

**Comment by attiks** [comment]
Segmentation faults for

- `phpunit tests/ExternalLookupTest.php`
- `phpunit tests/OchaPresenceExternalIdTest.php`

**Comment by attiks** [comment]
```
An exception occurred while executing a query: SQLSTATE[42000]: Syntax erro  
  r or access violation: 1142 DROP command denied to user 'ocha_api'@'172.18.  
  0.3' for table `test`.`country_version`       
```

**Comment by cafuego** [comment]
Found the issue, back to you for some more failing tests :-)

**Pull request merged**
